import { prisma } from "@/lib/prisma";

export type RecentExam = {
  id: string;
  title: string;
  createdAt: Date;
  questionCount: number;
  /** null when the student has generated the paper but not attempted it yet */
  score: number | null;
  /** id of the latest submitted attempt for direct review navigation */
  latestAttemptId: string | null;
};

export type DashboardData = {
  totalExamsTaken: number;
  /** average score across all submitted attempts, as a percentage; null when nothing attempted */
  avgScorePercent: number | null;
  recentExams: RecentExam[];
};

export async function getDashboardData(userId: string): Promise<DashboardData> {
  const [recent, allSubmittedAttempts] = await Promise.all([
    // The 5 most recently generated papers
    (prisma as any).exam.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take: 5,
      include: {
        _count: { select: { questions: true } },
        attempts: {
          where: { submittedAt: { not: null } },
          orderBy: { submittedAt: "desc" },
          select: { id: true, score: true, roomId: true },
        },
      },
    }),
    // Every submitted attempt
    (prisma as any).attempt.findMany({
      where: { userId, submittedAt: { not: null } },
      select: {
        score: true,
        roomId: true,
        exam: { select: { _count: { select: { questions: true } } } },
      },
    }),
  ]);

  // Filter out room attempts (solo attempts have no roomId)
  const scoredAttempts = (allSubmittedAttempts as any[]).filter(
    (a) => !a.roomId
  );

  // Average the per-exam NEET percentages: (score / (questions * 4)) * 100, clamped to 0-100%
  const percentages = scoredAttempts
    .filter((a) => a.exam._count.questions > 0 && a.score !== null)
    .map((a) => {
      const maxMarks = a.exam._count.questions * 4;
      const score = a.score ?? 0;
      return Math.max(0, Math.min(100, (score / maxMarks) * 100));
    });

  const avgScorePercent =
    percentages.length > 0
      ? percentages.reduce((sum, p) => sum + p, 0) / percentages.length
      : null;

  return {
    totalExamsTaken: scoredAttempts.length,
    avgScorePercent,
    recentExams: (recent as any[]).map((exam) => {
      const soloAttempts = (exam.attempts as any[]).filter((a) => !a.roomId);
      return {
        id: exam.id,
        title: exam.title,
        createdAt: exam.createdAt,
        questionCount: exam._count.questions,
        score: soloAttempts[0]?.score ?? null,
        latestAttemptId: soloAttempts[0]?.id ?? null,
      };
    }),
  };
}

/**
 * Returns all mock exams generated by the user, ordered latest first.
 */
export async function getAllExams(userId: string): Promise<RecentExam[]> {
  const exams = await (prisma as any).exam.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
    include: {
      _count: { select: { questions: true } },
      attempts: {
        where: { submittedAt: { not: null } },
        orderBy: { submittedAt: "desc" },
        select: { id: true, score: true, roomId: true },
      },
    },
  });

  return (exams as any[]).map((exam) => {
    const soloAttempts = (exam.attempts as any[]).filter((a) => !a.roomId);
    return {
      id: exam.id,
      title: exam.title,
      createdAt: exam.createdAt,
      questionCount: exam._count.questions,
      score: soloAttempts[0]?.score ?? null,
      latestAttemptId: soloAttempts[0]?.id ?? null,
    };
  });
}


